---
title: "Joins"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(palmerpenguins)
library(lubridate)
```

## Joins

```{r} ##didn't work on PC?? Addins > paste as tribble. from HTML table}
animals <- tibble::tribble(
  ~`location	species	maturity`,
       "lagoon\tbobcat\tadult",
     "bluff\tcoyote\tjuvenile",
           "creek\tfox\tadult",
    "oaks\tsquirrel\tjuvenile",
        "bluff\tbobcat\tadult",
                         "⬀셵Ź"
  )


sites <- tibble::tribble(
           ~`location	full_site_name	jurisdiction`,
                    "beach\tGoleta Beach\tSB City",
                       "lagoon\tUCSB Lagoon\tUCSB",
                    "bluff\tEllwood Mesa\tSB City",
                  "oaks\tFremont Campground\tUSFS",
                                          "ﴀ\177Ā"
           )


```

```{r}
animals <- tibble::tribble(
             ~location,   ~species,  ~maturity,
              "lagoon",   "bobcat",    "adult",
               "bluff",   "coyote", "juvenile",
               "creek",      "fox",    "adult",
                "oaks", "squirrel", "juvenile",
               "bluff",   "bobcat",    "adult"
             )
sites <- tibble::tribble(
           ~location,      ~full_site_name, ~jurisdiction,
             "beach",       "Goleta Beach",     "SB City",
            "lagoon",        "UCSB Lagoon",        "UCSB",
             "bluff",       "Ellwood Mesa",     "SB City",
              "oaks", "Fremont Campground",        "USFS"
           )
```

### Full join

```{r}
full_join_example <- full_join(animals, sites)
```

### Left join

```{r}
left_join_ex <- left_join(animals, sites)
right_join_ex <- right_join(animals, sites)
```

### Inner join

```{r}
inner_join_ex <- inner_join(animals, sites, by = "location")
sites_2 <- sites |> 
  rename(loc = location)
```

#### Example of joining when key variables have non-matching names.

```{r}
nonmatching <- full_join(animals, sites_2, by = c("location" = "loc"))
```

## Filtering joins

### Semi join

```{r}
semi_join_ex <- semi_join(animals, sites)
```

### Anti join

```{r}
anti_join_ex <- anti_join(animas, sites, by = "location")
```

## Wrangling
```{r}
penguins_subset <- penguins |> 
  filter(island %in% c("Biscoe", "Dream")) |> 
  select(-year, -sex) |> 
  mutate(body_mass_kg = body_mass_g / 1000)
```

### Dates with lubridate
```{r}
my_date <- "03-15-1998"
lubridate::mdy(my_date)

my_date <- "11/7/2003"
lubridate::dmy(my_date)

my_date <- "08-Jun-1974"
lubridate::dmy(my_date)

my_date <- "19610518"
my_real_date <- lubridate::ymd(my_date)
```

```{r}
lubridate::ymd("1942-08-30")
lubridate::mdy("09/22/84")
```

```{r}
time <- "2020-08-12 11:18"
time <- ymd_hm(time)
time
class(time)
```

###Convert timezones -- Olson timezone names?
```{r}
with_tz(time, "America/Los_Angeles")
with_tz(time, "Australia/Sydney")
my_time <- lubridate::ymd_hms(time)
year(my_time)
day(my_time)
month(my_time)
hour(my_time)
minute(my_time)
second(my_time)
```

```{r}
teddy_bday <- lubridate::ymd("20170615")
wday(teddy_bday, label = TRUE)

my_bday <- lubridate::ymd("19970226")
wday(my_bday, label = TRUE)
week(my_bday)
```

```{r}
urchin_counts <- tribble(
  ~date, ~species, ~size_mm,
  "10/3/2020", "purple", 55,
  "10/4/2020", "red", 48,
  "11/17/2020", "red", 67
)

urchin_ymd <- urchin_counts |> 
  mutate(date = mdy(date)) |> 
  mutate(year = year(date)) |> 
  mutate(month = month(date)) |> 
  mutate(day = day(date))
class(urchin_ymd$date)

```

```{r}
day_1 <- ymd("2020-01-06")
day_2 <- ymd("2020-05-18")

time_interval <- interval(day_1, day_2)

time_length(time_interval, "year")
```

